export const REDUCER_NAME = 'allDesigners';

export const ALL_DESIGNERS_REQUEST = `${REDUCER_NAME}/ALL_DESIGNERS_REQUEST`;
export const ALL_DESIGNERS_RESPONSE = `${REDUCER_NAME}/ALL_DESIGNERS_RESPONSE`;
export const ALL_DESIGNERS_ERROR = `${REDUCER_NAME}/ALL_DESIGNERS_ERROR`;