export const REDUCER_NAME = 'allClubs';

export const ALL_CLUBS_REQUEST = `${REDUCER_NAME}/ALL_CLUBS_REQUEST`;
export const ALL_CLUBS_RESPONSE = `${REDUCER_NAME}/ALL_CLUBS_RESPONSE`;
export const ALL_CLUBS_ERROR = `${REDUCER_NAME}/ALL_CLUBS_ERROR`;